name: Continuous Integration (MSVC)

on:
  push:
    branches: [ master ]
    tags: ['*']
    paths-ignore: ['**.md']
  pull_request:
    branches: [ master ]
    paths-ignore: ['**.md']
  workflow_dispatch:

env:
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - name: Linux GCC
            os: ubuntu-latest
            extra-options: >-
              -DCMAKE_INSTALL_PREFIX=/usr
              -DVCPKG_TARGET_TRIPLET="x64-linux-release"

          - name: MSVC(x64)
            os: windows-latest
            arch: x64
            extra-options: >-
              -DVCPKG_OVERLAY_TRIPLETS="cmake/triplets"
              -DVCPKG_TARGET_TRIPLET="x64-windows-static-release"
              -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
              -DCMAKE_IGNORE_PATH="C:/Strawberry/perl/bin;C:/Strawberry/c/lib"

          - name: MSVC(x86)
            os: windows-latest
            arch: x86
            extra-options: >-
              -DVCPKG_OVERLAY_TRIPLETS="cmake/triplets"
              -DVCPKG_TARGET_TRIPLET="x86-windows-static-release"
              -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
              -DCMAKE_IGNORE_PATH="C:/Strawberry/perl/bin;C:/Strawberry/c/lib"

    steps:
      - uses: actions/checkout@v4

      - name: Setup vcpkg and NuGet
        shell: bash
        run: |
          set -euo pipefail

          cd "${{ env.VCPKG_INSTALLATION_ROOT }}"

          NUGET=$(vcpkg fetch nuget | tail -n 1)
          GH_PACKAGES_URL="https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

          "$NUGET" sources add \
            -source "$GH_PACKAGES_URL" \
            -storepasswordincleartext \
            -name "GitHub" \
            -username "${{ github.repository_owner }}" \
            -password "${{ secrets.GITHUB_TOKEN }}"

          "$NUGET" setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -source "$GH_PACKAGES_URL"

      - name: Configure
        shell: bash
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_WERROR=ON -DENABLE_LTO=ON \
            -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_INSTALLATION_ROOT }}/scripts/buildsystems/vcpkg.cmake" \
            ${{ matrix.config.extra-options }}

      - name: Build
        run: cmake --build build --config "Release"

      - name: Test
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd demotest
          pip install pyyaml joblib
          python demotest --jobs 4 --port ../build/src/woof

      - name: Package
        run: |
          cd build
          cpack

      - name: Upload AppImage
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: Woof-AppImage
          path: build/*.appimage

      - name: Upload artifacts
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: Win-${{ matrix.config.arch }}
          path: build/*.zip

      - name: Extract Version Number
        shell: bash
        run: echo "VERSION=${GITHUB_REF##*_}" >> $GITHUB_ENV

      - name: Release
        if: ${{ contains(github.ref, 'tags') }}
        uses: ncipollo/release-action@v1
        with:
          name: Woof! ${{ env.VERSION }}
          bodyFile: CHANGELOG.md
          allowUpdates: true
          artifacts: build/*.zip
